// <auto-generated />
using System;
using BibliothequeApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bibliotheque.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529151236_InitPostgres")]
    partial class InitPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BibliothequeApp.Models.Abonnement", b =>
                {
                    b.Property<int>("Id_abonnement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_abonnement"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("CodeAbonnement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_membre")
                        .HasColumnType("integer");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id_abonnement");

                    b.HasIndex("Id_membre");

                    b.ToTable("Abonnements");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Emprunt", b =>
                {
                    b.Property<int>("Id_emprunt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_emprunt"));

                    b.Property<string>("CodeEmprunt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Date_emprunt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Date_retour_effective")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date_retour_prevue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_livre")
                        .HasColumnType("integer");

                    b.Property<int>("Id_membre")
                        .HasColumnType("integer");

                    b.Property<decimal>("Penalite")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id_emprunt");

                    b.HasIndex("Id_livre");

                    b.HasIndex("Id_membre");

                    b.ToTable("Emprunts");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Livre", b =>
                {
                    b.Property<int>("Id_livre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_livre"));

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Categorie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Disponibilite")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Disponible");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteDisponible")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id_livre");

                    b.ToTable("Livres");

                    b.HasData(
                        new
                        {
                            Id_livre = 1,
                            Auteur = "Paulo Coelho",
                            Disponibilite = "Disponible",
                            ISBN = "9782266066838",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8242088-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "L'Alchimiste"
                        },
                        new
                        {
                            Id_livre = 2,
                            Auteur = "George Orwell",
                            Disponibilite = "Disponible",
                            ISBN = "9782070360833",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8241625-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "1984"
                        },
                        new
                        {
                            Id_livre = 3,
                            Auteur = "Antoine de Saint-Exupéry",
                            Disponibilite = "Disponible",
                            ISBN = "9782070612758",
                            ImageUrl = "https://covers.openlibrary.org/b/id/7919477-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "Le Petit Prince"
                        },
                        new
                        {
                            Id_livre = 4,
                            Auteur = "J.K. Rowling",
                            Disponibilite = "Disponible",
                            ISBN = "9782253044932",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8251599-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "Harry Potter à l'École des Sorciers"
                        },
                        new
                        {
                            Id_livre = 5,
                            Auteur = "Victor Hugo",
                            Disponibilite = "Disponible",
                            ISBN = "9782253096344",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8415236-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "Les Misérables"
                        },
                        new
                        {
                            Id_livre = 6,
                            Auteur = "Yuval Noah Harari",
                            Disponibilite = "Disponible",
                            ISBN = "9782226257017",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8255978-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "Sapiens"
                        },
                        new
                        {
                            Id_livre = 7,
                            Auteur = "J.R.R. Tolkien",
                            Disponibilite = "Disponible",
                            ISBN = "9782253050766",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8241708-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "Le Seigneur des Anneaux"
                        },
                        new
                        {
                            Id_livre = 8,
                            Auteur = "Miguel de Cervantes",
                            Disponibilite = "Disponible",
                            ISBN = "9782253084496",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8380151-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "Don Quichotte"
                        },
                        new
                        {
                            Id_livre = 9,
                            Auteur = "Jane Austen",
                            Disponibilite = "Disponible",
                            ISBN = "9782253064688",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8415226-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "Orgueil et Préjugés"
                        },
                        new
                        {
                            Id_livre = 10,
                            Auteur = "Alexandre Dumas",
                            Disponibilite = "Disponible",
                            ISBN = "9782253053261",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8254066-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "Le Comte de Monte-Cristo"
                        },
                        new
                        {
                            Id_livre = 11,
                            Auteur = "Gabriel García Márquez",
                            Disponibilite = "Disponible",
                            ISBN = "9782253044529",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8252886-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "Cent Ans de Solitude"
                        },
                        new
                        {
                            Id_livre = 12,
                            Auteur = "Dan Brown",
                            Disponibilite = "Disponible",
                            ISBN = "9782253050995",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8234605-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "Le Code Da Vinci"
                        },
                        new
                        {
                            Id_livre = 13,
                            Auteur = "J.R.R. Tolkien",
                            Disponibilite = "Disponible",
                            ISBN = "9782253053681",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8415328-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "Le Hobbit"
                        },
                        new
                        {
                            Id_livre = 14,
                            Auteur = "Émile Zola",
                            Disponibilite = "Disponible",
                            ISBN = "9782253052654",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8385577-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "La Bête humaine"
                        },
                        new
                        {
                            Id_livre = 15,
                            Auteur = "Jonathan Riley-Smith",
                            Disponibilite = "Disponible",
                            ISBN = "9782746004092",
                            ImageUrl = "https://covers.openlibrary.org/b/id/8380242-M.jpg",
                            Quantite = 1,
                            QuantiteDisponible = 1,
                            Titre = "Croisades"
                        });
                });

            modelBuilder.Entity("BibliothequeApp.Models.Membre", b =>
                {
                    b.Property<int>("Id_membre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_membre"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id_membre");

                    b.ToTable("Membres");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Notification", b =>
                {
                    b.Property<int>("Id_notification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_notification"));

                    b.Property<DateTime?>("Date_envoie")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_membre")
                        .HasColumnType("integer");

                    b.Property<bool>("Lu")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id_notification");

                    b.HasIndex("Id_membre");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Penalite", b =>
                {
                    b.Property<int>("Id_penalite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_penalite"));

                    b.Property<DateTime?>("Date_")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_emprunt")
                        .HasColumnType("integer");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Raison")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id_penalite");

                    b.HasIndex("Id_emprunt");

                    b.ToTable("Penalites");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Reservation", b =>
                {
                    b.Property<int>("Id_reservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_reservation"));

                    b.Property<string>("CodeReservation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("Date_expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date_reservation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_livre")
                        .HasColumnType("integer");

                    b.Property<int>("Id_membre")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id_reservation");

                    b.HasIndex("Id_livre");

                    b.HasIndex("Id_membre");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Id_membre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Admin",
                            Password = "A6xnQhbz4Vx2HuGl4lXwZ5U2I8iziLRFnhP5eNfIRvQ=",
                            Prenom = "Système",
                            Role = "Administrateur",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("BibliothequeApp.Models.Abonnement", b =>
                {
                    b.HasOne("BibliothequeApp.Models.Membre", "Membre")
                        .WithMany("Abonnements")
                        .HasForeignKey("Id_membre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Emprunt", b =>
                {
                    b.HasOne("BibliothequeApp.Models.Livre", "Livre")
                        .WithMany("Emprunts")
                        .HasForeignKey("Id_livre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliothequeApp.Models.Membre", "Membre")
                        .WithMany("Emprunts")
                        .HasForeignKey("Id_membre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Notification", b =>
                {
                    b.HasOne("BibliothequeApp.Models.Membre", "Membre")
                        .WithMany("Notifications")
                        .HasForeignKey("Id_membre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Penalite", b =>
                {
                    b.HasOne("BibliothequeApp.Models.Emprunt", "Emprunt")
                        .WithMany("Penalites")
                        .HasForeignKey("Id_emprunt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprunt");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Reservation", b =>
                {
                    b.HasOne("BibliothequeApp.Models.Livre", "Livre")
                        .WithMany("Reservations")
                        .HasForeignKey("Id_livre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliothequeApp.Models.Membre", "Membre")
                        .WithMany("Reservations")
                        .HasForeignKey("Id_membre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Emprunt", b =>
                {
                    b.Navigation("Penalites");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Livre", b =>
                {
                    b.Navigation("Emprunts");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BibliothequeApp.Models.Membre", b =>
                {
                    b.Navigation("Abonnements");

                    b.Navigation("Emprunts");

                    b.Navigation("Notifications");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
